name: python311
channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - conda-forge
  - huggingface
  - nodefaults
dependencies:
  - python>=3.11,<=3.12
  - joblib>=1.3.2
  - pathos>=0.3.1
  - dill>=0.3.7
  - structlog>=23.1.0
  - orjson>=3.9.5
  - cached_property>=1.5.2
  - click>=8.1.7
  - boto3>=1.28.38
  - librosa>=0.10.1
  - supervisor>=4.2.5,<5.0.0
  - setuptools>=68.2.2,<69.0.0
  - setuptools-rust>=1.7.0,<2.0.0
  - wheel>=0.41.2,<0.42.0
  - flit>=3.9.0,<4.0.0
  - hatchling>=1.18.0,<2.0.0
  - vpython>=7.6.4,<8.0.0
  - nbdime>=3.2.1,<4.0.0
  - ipympl>=0.9.3,<0.10.0
  - cython>=3.0.2,<4.0.0
  - jupyterhub>=4.0.2,<5.0.0
  - jupyterlab<4.0.0a0
  - dask>=2023.9.1,<2024.0.0
  - notebook<7.0.0
  - nbconvert<7.0.0
  - jupytext>=1.15.1,<2.0.0
  - ipython>=8.15.0,<9.0.0
  - jupyter-panel-proxy>=0.1.0,<0.2.0
  - elyra>=3.15.0,<4.0.0
  - credstash>=1.17.1,<2.0.0
  - cryptography>=41.0.3,<42.0.0
  - lux>=0.5.1,<0.6.0
  - bqplot>=0.12.40,<0.13.0
  - hvplot>=0.8.4,<0.9.0
  - voila>=0.5.3,<0.6.0
  - tqdm>=4.66.1,<5.0.0
  - evidently>=0.4.4,<0.5.0
  - altair>=5.1.1,<6.0.0
  - lolviz>=1.4.4,<2.0.0
  - ipyvolume>=0.6.3,<0.7.0
  - ipywidgets>=8.1.1,<9.0.0
  - ipyleaflet>=0.17.4,<0.18.0
  - ipydatagrid>=1.2.0,<2.0.0
  - pythreejs>=2.4.2,<3.0.0
  - sidecar>=0.7.0,<0.8.0
  - ruff>=0.0.289,<0.0.290
  - black>=23.9.1,<24.0.0
  - nbqa>=1.7.0,<2.0.0
  - mypy>=1.5.1,<2.0.0
  - ipytest>=0.13.3,<0.14.0
  - nbcelltests>=0.2.3,<0.3.0
  - jupyter-dash>=0.4.2,<0.5.0
  - python-lsp-server>=1.8.0,<2.0.0
  - pylsp-mypy>=0.6.7,<0.7.0
  - python-lsp-black>=1.3.0,<2.0.0
  - python-lsp-ruff>=1.5.1,<2.0.0
  - pyls-isort>=0.2.2,<0.3.0
  - jupyterlab-spellchecker<=0.8.4
  - jupyterlab-fonts>=2.1.1,<3.0.0
  - dask-labextension<7.0.0
  - jupyterlab-git>=0.42.0,<0.43.0
  - jupyterlab-fasta>=3.3.0,<4.0.0
  - jupyterlab-geojson>=3.4.0,<4.0.0
  - jupyterlab-katex>=3.4.0,<4.0.0
  - jupyterlab-mathjax3>=4.3.0,<5.0.0
  - jupyterlab-vega3>=3.3.0,<4.0.0
  - theme-darcula>=4.0.0,<5.0.0
  - conda-lock>=2.3.0,<3.0.0
  - filprofiler>=2023.3.1,<2024.0.0
  - yappi>=1.4.0,<2.0.0
  - viztracer>=0.15.6,<0.16.0
  - loguru>=0.7.2,<0.8.0
  - icecream>=2.1.3,<3.0.0
  - appdirs>=1.4.4,<2.0.0
  - jupyter-lsp>=2.2.0,<3.0.0
  - pip>=23.2.1
  - pip:
      - jupyter-contrib-nbextensions>=0.7.0,<0.8.0
      - jupyter-nbextensions-configurator>=0.6.3,<0.7.0
      - python-build>=0.2.13,<0.3.0
      - soundfile>=0.12.1
      - sagemaker-training>=4.7.0,<5.0.0
      - multi-model-server>=1.1.11,<2.0.0
      - visualpython>=2.4.9,<3.0.0
      - jupyter-server>=2.7.3,<3.0.0
      - jupyterlab-autoversion>=0.3.6,<0.4.0
      - lineapy>=0.2.3,<0.3.0
      - pd-replicator>=0.0.1,<0.0.2
      - ipyaggrid>=0.5.0,<0.6.0
      - nb-black>=1.0.7,<2.0.0
      - jupyter-nbrequirements>=0.7.3,<0.8.0
      - jupyterlab-code-formatter>=2.2.1,<3.0.0
      - lckr-jupyterlab-variableinspector>=3.0.9,<4.0.0
      - jupyterlab-visualpython>=2.4.9,<3.0.0
      - jupyterlab-autoplot>=0.5.0,<0.6.0
      - jupyterlab-widgets>=3.0.9,<4.0.0
      - jupyterlab-mathjax2>=4.0.0,<5.0.0
      - jupyterlab-tensorboard-pro>=0.8.0,<0.9.0
      - jupyterlab-theme-solarized-dark>=3.0.0,<4.0.0
      - jupyterlab-lsp>=4.2.0,<5.0.0
      - qgrid>=1.3.1,<2.0.0
      - uvicorn>=0.23.2,<0.24.0
