# prefer pip
name: base
channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - conda-forge
  - huggingface
  - nodefaults
dependencies:
  - python~=3.11
  - pip>=23.2.1
  - appdirs>=1.4.4
  - conda-lock>=2.3.0
  - wheel>=0.41.2
  - python-build>=1.0.0
  - flit>=3.9.0
  - virtualenv>=20.20.0
  - poetry>=1.6.1
  - pip:
      - poetry-conda>=0.1.0
      - poetry-multiproject-plugin>=1.3.1
      - nox>=2023.4.22
      - nox-poetry>=1.0.3
      - hatchling>=1.18.0
