# prefer pip
name: python311
channels:
  - nvidia
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11,<=3.12
  - pip>=23.2.1
  # accelerated
  - blas=*=*mkl
  - nvidia::cuda-nvcc~=11.8
  - nvidia::cuda-toolkit~=11.8
  - mkl-devel
  - openvino
  - libopenvino-intel-cpu-plugin
  - libopenvino-auto-plugin
  - libopenvino-pytorch-frontend
  - libopenvino-ir-frontend
  - libopenvino-onnx-frontend
  - intel::neural-compressor
  - tbb
  # utils
  - ffmpeg
  - av>=10.0.0
  # core
  - cffi
  - psutil
  - pybind11
  - gitpython
  - sympy
  - numpy
  - numexpr
  - cupy
  - cython
  - numba
  - pathos
  - dill
  - cached_property
  - transonic
  - pandas
  - geopandas
  - dask
  - pythran
  # # thinc
  - thinc
  - spacy
  # # torch
  - pytorch::pytorch~=2.0.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - faiss-gpu
  - pytorch-lightning
  - timm
  - diffusers
  # # huggingface
  - huggingface::transformers
  - huggingface::tokenizers
  - huggingface::datasets
  - accelerate
  - huggingface::huggingface_hub
  # # misc
  - scikit-learn
  - pillow
  - opencv
  - nltk
  - librosa
  - pyctcdecode
  - beautifulsoup4
  - chardet
  - SQLAlchemy
  - psycopg2-binary
  - pgvector
  - requests
  - requests-toolbelt
  - sentencepiece
  - dataclasses
  - protobuf
  - tensorly
  - einops
  - tqdm
  - optuna
  - lxml
  - aiohttp
  - networkx
  - pytest
  - jinja2
  - dataclasses-json
  - async-timeout
  - pexpect
  - pytest-xdist
  - parameterized
  - tenacity
  - ftfy
  # kernel
  - ipykernel
  - xeus-python
