# prefer pip
name: python311
channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - intel
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<=3.12
  - pip>=23.2.1
  - ipykernel
  - xeus-python
  # accelerated
  - cudatoolkit~=11.8.0
  - cudnn~=8.8.0
  - nccl
  - mkl-devel
  - blas=*=*mkl
  - openvino
  - libopenvino-intel-cpu-plugin
  - libopenvino-auto-plugin
  - libopenvino-pytorch-frontend
  - libopenvino-ir-frontend
  - libopenvino-onnx-frontend
  - tbb
  # utils
  - ffmpeg
  - av>=10.0.0
  - faiss-gpu
  # core
  - cffi
  - pybind11
  - numpy
  - cython
  - pythran
  - numba
  - transonic
  # pip
  - pip:
      # huggingface
      - "transformers>=4.3.2"
      - "tokenizers"
      - "datasets"
      - "accelerate>=0.20.3"
      - "timm"
      # support
      - "beautifulsoup4"
      - "codecarbon>=1.2.0"
      - "dataclasses"
      - "ftfy"
      - "dill"
      - "pathos"
      - "parameterized"
      - "pytest"
      - "pytest-xdist"
      - "parameterized"
      - "psutil"
      - "evaluate"
      - "protobuf"
      - "cached_property"
      - "tqdm"
      # core
      - "scikit-learn"
      - "natten"
      - "nltk"
      # agents
      - "diffusers"
      - "sentencepiece"
      - "langchain[all]"
      # data
      - "decord"
      - "kenlm"
      - "librosa"
      - "pyctcdecode"
      - "phonemizer"
      - "opencv-python"
      - "Pillow"
      # deployment/integrations
      - "deepspeed"
      - "optimum[all]"
      - "sagemaker"
      - "fairscale"
      - "optuna"
      - "sigopt"
      - "ray[all]"
      - "dask[all]"
      - "olive-ai"
      - "nvidia-pytriton"
      # onnx
      - "onnxruntime"
      - "onnxruntime-gpu"
      - "onnxruntime-tools"
      - "onnxconverter-common"
      # tensorflow
      - "tensorflow>=2.13.0"
      - "keras"
      - "tensorflow-text"
      - "keras-nlp"
      - "tensorboard"
      - "tf2onnx"
      # serving
      - "pydantic"
      - "fastapi"
      - "starlette"
      - "uvicorn"
      # torch
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - "torch>=2.0.1"
      - "torchaudio"
      - "torchvision"
      - "pytorch-lightning"
      # jax
      - --extra-index-url https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - "jax[cuda12_local]>=0.4.16"
      - "flax>=0.7.4"
      - "optax>=0.1.7"
      # debug
      - "sliceguard"
      - "spotlight"
      - "perspective-python"
      - "viztracer"
      - "yappi"
      - "filprofiler"
