name: base
channels:
  - conda-forge
dependencies:
  - python>=3.11,<=3.12
  - pip>=23.2.1
  - poetry>=1.6.1
  - ca-certificates
  - certifi
  - openssl
  - mamba
  - appdirs
  - wheel
  - setuptools
  - setuptools-rust
  - flit
  - hatchling
  - python-build
  - packaging
  - libsolv
  - pycosat
  - conda-libmamba-solver
  - conda-lock
  - conda-pack
  - conda-build
  - virtualenv
  - zstandard
  - joblib
  - psutil
  - pathos
  - dill
  - texlab
  - chktex
  - ipykernel
  - xeus-python
  - black
  - ruff
  - nox
  - mypy
  - nbqa
  - pre-commit
  - commitizen
  - watchdog
  - pip:
      - -r ./requirements.txt
